apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
namespace: prod
commonAnnotations:
  supported-by: clop@outlook.com
labels:
  - includeSelectors: false
    pairs:
      project: instavote  

# replicas:
# - count: 2
#   name: vote
# namespace: staging
# commonAnnotations:
#   supported-by: sre@example.com
# labels:
# - includeSelectors: false
#   pairs:
#     project: instavote
patches:
- path: service.yaml
- path: preview-service.yaml
- path: rollout.yaml
